name: "npm dependencies setup"
description: "Setup Node (with npm cache), and install via npm ci"

inputs:
  working-directory:
    required: true
    description: Directory to install dependencies

runs:
  using: "composite"
  steps:
    - name: Setup Node.js (with npm cache)
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: npm
        cache-dependency-path: "${{ inputs.working-directory }}/package-lock.json"

    - name: Install dependencies
      shell: bash
      run: npm ci --legacy-peer-deps
      working-directory: ${{ inputs.working-directory }}
