name: Static code checking
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client_code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Run ESLint
        run: npx eslint . --max-warnings 0
        working-directory: client
  client_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Build
        run: npm run build
        working-directory: client
  server_code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Run ESLint
        run: npx eslint . --max-warnings 0
        working-directory: server
  server_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Build
        run: npm run build
        working-directory: server
