name: Static code checking
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client_code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout client code
        run: cd client

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Run ESLint
        run: npx eslint . --max-warnings 0
  client_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout client code
        run: cd client

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Build
        run: npm run build
