name: Static code checking
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Linting client code using ESLint
        run: npx eslint . --max-warnings 0
        working-directory: client

      - name: Linting server code using ESLint
        run: npx eslint . --max-warnings 0
        working-directory: server
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/npm-setup

      - name: Build server
        run: npm run build
        working-directory: server

      - name: Build client
        run: npm run build
        working-directory: client
        env:
          NEXT_PUBLIC_TRPC_URL: dummy
